server:
  port: 8085

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 10
    open-in-view: false

    mvc:
      path match:
        matching-strategy: ant_path_matcher
        default_batch_fetch_size: 10

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: info
  com.jpa: debug

spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
