server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/moyeomoyeo?createDatabaseIfNotExist=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: info
  com.jpa: debug

